# Generated by Django 5.2.8 on 2025-11-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_alter_cliente_table_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad_stock', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'repuesto',
            },
        ),
        migrations.CreateModel(
            name='ServicioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo_id', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('repuesto_usado', models.BooleanField(default=False)),
                ('repuesto_id', models.IntegerField(blank=True, null=True)),
                ('cantidad_repuesto', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ordenservicio',
            },
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='vehiculo',
            table='vehiculo',
        ),
    ]
